<a href="https://colab.research.google.com/github/bhoomika3007/24_SheCodes_HealthAndWellness/blob/main/del_lab_2_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

multitasking with early stopping in a neural network scenario

In [45]:
import tensorflow as tf
from tensorflow.keras import Sequential,Model
from tensorflow.keras.layers import Dense,Flatten,Input
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.utils import to_categorical

In [46]:
(x_train,y_train),(x_test,y_test)=tf.keras.datasets.mnist.load_data()

In [47]:
x_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [48]:
x_test

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [49]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [84]:
x_train = x_train.reshape(-1, 28 * 28) / 255.0
x_test = x_test.reshape(-1, 28 * 28) / 255.0

y_parity_train = (y_train % 2 == 0).astype(int)
y_parity_test = (y_test % 2 == 0).astype(int)

y_digit_train = y_train
y_digit_test = y_test

In [96]:
inputs = Input(shape=(784,))
x = Dense(128, activation='relu')(inputs)
x = Dense(64, activation='relu')(x)
o1 = Dense(1, activation='sigmoid', name='out1')(x)  # Binary classification
o2 = Dense(10, activation='softmax', name='out2')(x)  # Multi-class classification


In [86]:
model=Model(inputs=inputs,outputs=[o1,o2])

In [87]:
model.compile(optimizer='adam',loss={'out1':'binary_crossentropy','out2':'sparse_categorical_crossentropy'},
              metrics={'out1':'accuracy','out2':'accuracy'})

In [91]:
early_stop=EarlyStopping(monitor='val_loss',patience=3,restore_best_weights=True)

In [93]:
history=model.fit(
    x_train,
     {'out1':y_parity_train,'out2':y_digit_train},
    validation_data=(x_test,
     {'out1':y_parity_test,'out2':y_digit_test},
                     ),
    callbacks=[early_stop],
    epochs=20,
    batch_size=64)

Epoch 1/20
938/938 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - loss: 2.0198 - out1_accuracy: 0.8343 - out1_loss: 0.3587 - out2_accuracy: 0.3010 - out2_loss: 1.6610 - val_loss: 1.9956 - val_out1_accuracy: 0.8386 - val_out1_loss: 0.3516 - val_out2_accuracy: 0.3092 - val_out2_loss: 1.6432
Epoch 2/20
938/938 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 2.0107 - out1_accuracy: 0.8367 - out1_loss: 0.3550 - out2_accuracy: 0.2971 - out2_loss: 1.6556 - val_loss: 2.0019 - val_out1_accuracy: 0.8364 - val_out1_loss: 0.3535 - val_out2_accuracy: 0.3168 - val_out2_loss: 1.6476
Epoch 3/20
938/938 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 2.0111 - out1_accuracy: 0.8355 - out1_loss: 0.3573 - out2_accuracy: 0.3032 - out2_loss: 1.6539 - val_loss: 1.9803 - val_out1_accuracy: 0.8422 - val_out1_loss: 0.3482 - val_out2_accuracy: 0.3127 - val_out2_loss: 1.6313
Epoch 4/20
938/938 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 1.9990 - out1_accuracy: 0.8386 - out1_loss: 0.3505 - out2_accuracy: 0.3065 - out2_loss: 1.6485 - val_los

In [94]:
stopped_epoch = early_stop.stopped_epoch
print(f"Early stopping occurred at epoch {stopped_epoch + 1}")


Early stopping occurred at epoch 17


In [95]:
model.evaluate(x_test, {
    'out2': y_digit_test,
    'out1': y_parity_test
})

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.9656 - out1_accuracy: 0.8385 - out1_loss: 0.3485 - out2_accuracy: 0.3375 - out2_loss: 1.6170


[1.915739893913269,
 0.330059677362442,
 1.585404634475708,
 0.8525000214576721,
 0.33980000019073486]